2022 11 08 8장 경계
LetsSwifty/clean-code pull request #13
Opened 2022-11-08 12:34 UTC by k-nh

8장 완료했습니다 어렵꾼요...ㅠ

2022-11-09 00:59 UTC, gaeng2y requested changes

2022-11-09 00:59 UTC, gaeng2y commented on 8장_경계/chapter8.md
> +    private Map sensors = new HasMap();
여기두!

2022-11-09 00:59 UTC, gaeng2y commented on 8장_경계/chapter8.md
> +Map<String, Sensor> sensors = new HasMap<Sensor>();
요기두

2022-11-09 00:59 UTC, gaeng2y commented on 8장_경계/chapter8.md
> +Map sensors = new HasMap();
HashMap()

으로 수정 부탁드려욯ㅎㅎ
(오타 찾았다)

2022-11-09 00:59 UTC, gaeng2y commented on 8장_경계/chapter8.md
> +예시3과 같이 캡슐화를 통해 경계 인터페이스인 `Map`을 `Sensor` 안으로 숨긴다면 `Map` 인터페이스가 변할 경우에도 나머지 프로그램에 영향을 미치지 않는다. 또한 캡슐화를 통해 사용자는 원하는 기능만을 공개할 수 있고 사용자의 코드를 보호할 수 있다.
OOP에서는 캡슐화를 얼마나 잘쓰냐에 따라 좋은 코드가 될 수 있는 것 같네요

2022-11-09 02:27 UTC, k-nh commented on 8장_경계/chapter8.md
> +Map sensors = new HasMap();
으앗 !

2022-11-09 08:21 UTC, heejin342 commented
저도 읽으면서 막 와닿지 않았습니다... 자바여서 그런가,, 
테스트 코드를 빠르게 공부해야겠군요! 
고생 많으셨습니다.

2022-11-09 08:21 UTC, heejin342 approved these changes

2022-11-09 15:29 UTC, kangddong approved these changes

2022-11-10 00:48 UTC, gaeng2y commented
나리님 오타 수정……………

2022-11-10 07:19 UTC, gaeng2y approved these changes

2022-11-10 07:20 UTC, merged