2022 11 11 9장 단위 테스트
LetsSwifty/clean-code pull request #14
Opened 2022-11-11 01:27 UTC by heejin342

강의 학습 중 Quick/Nimble을 봐보긴했지만, 제대로 사용을 못해서 자바 코드로 작성하였습니다. 
테스트 코드의 흐름이랑 유형만 보는거니 자바 코드라도 어렵지 않을 거라고 판단했습니다. 
공부를 좀 해서 이번달 안으로 swift 로 적용해서 바꿔놓고, 새로운 issue 만들어서 PR 올리겠습니다.

감사합니다.

2022-11-11 01:30 UTC, heejin342 commented on 9장_단위_테스트/chapter9.md
> +#9장 단위 테스트
H1 타이틀로 수정하겠습니다  ..

2022-11-11 03:01 UTC, gaeng2y requested changes

2022-11-11 03:01 UTC, gaeng2y commented on 9장_단위_테스트/chapter9.md
> +TEMPLATE METHOD 패턴을 사용하면 중복을 제거할 수 있다. given/when 부분을 부모 클래스에 두고 then 부분을 자식 클래스에 두면 된다. 아니면 완전히 독자적인 테스트 클래스를 만들어 @Before 함수에 given/when 부분을 넣고 @Test 함수에 then 부분을 넣어도 된다.
### 참고자료
[템플릿 메서드 패턴](https://refactoring.guru/ko/design-patterns/template-method)

2022-11-11 08:48 UTC, k-nh approved these changes
수고하셨습니다 👏

2022-11-13 07:47 UTC, kangddong approved these changes
고생하셨습니다 ~

2022-11-13 07:52 UTC, gaeng2y commented
오타 수정해서 커밋해주시면 저두 approve하겠읍니다!

2022-11-13 08:09 UTC, heejin342 commented on 9장_단위_테스트/chapter9.md
> +TEMPLATE METHOD 패턴을 사용하면 중복을 제거할 수 있다. given/when 부분을 부모 클래스에 두고 then 부분을 자식 클래스에 두면 된다. 아니면 완전히 독자적인 테스트 클래스를 만들어 @Before 함수에 given/when 부분을 넣고 @Test 함수에 then 부분을 넣어도 된다.
반영해서 작성했습니당

2022-11-13 14:42 UTC, gaeng2y approved these changes

2022-11-13 15:01 UTC, merged