Chapter11
LetsSwifty/clean-code pull request #16
Opened 2022-11-15 19:24 UTC by kangddong

아래로 갈수록 자바에 관한건 많이 걷어낸게 있는데요
Swift 관점에서 연관성이 너무 적어보이는 애들을 굳이 같이  작성해야할까 .. 라는 의문점에서 삭제했습니다...!
추상 팩토리 패턴은 Swift로 구현을해보았고요, DIP와 Test코드도 작성하고 싶었는데 아직 DIP에 대해서 이해도가 낮아서 일단 PR 먼저 올리게되었습니다 ! 너무 어렵네요 ㅜㅜㅜ

2022-11-17 01:02 UTC, gaeng2y requested changes

2022-11-17 01:02 UTC, gaeng2y commented on 11장_시스템/chapter11.md
> +```java MyService myService = (MyService)(jndiContext.lookup ("NameOfMyService");```
위아래로 공백을 둬야할 것 같아요!

2022-11-17 01:02 UTC, gaeng2y commented on 11장_시스템/chapter11.md
> +버그가 숨이들기 쉬워지고, 스토리를 구현하기 어려워지는 탓이다. 기민성이 떨어지면 생산성이 낮아져 TDD가 제공하는 장점이 사라진다.
숨이들기 -> 숨어들기

2022-11-19 20:31 UTC, k-nh requested changes

2022-11-20 11:58 UTC, kangddong commented on 11장_시스템/chapter11.md
> +이것이 초기화 지연(Lazy Initialization) 혹은 계산 지연(Lazy Evaluation)이라는 기법이다. <br>
어떤 경우에도 nil를 반환하지않는다..라는게 확신이 없어서 추가를 못했었어요 ㅜㅜ

2022-11-20 12:03 UTC, kangddong commented
오타 찾아내시는거 진짜 대단합니다 .. .. 감사해요

2022-11-21 09:58 UTC, gaeng2y approved these changes

2022-11-26 05:49 UTC, heejin342 commented
확인했습니다 :> 고생 많으셨어요

2022-11-26 05:49 UTC, heejin342 approved these changes

2022-11-27 23:52 UTC, k-nh approved these changes

2022-11-28 00:21 UTC, merged