2022 10 26 1장 깨끗한 코드
LetsSwifty/clean-code pull request #4
Opened 2022-10-26 09:50 UTC by gaeng2y

확인 부탁드려요!

2022-10-26 09:56 UTC, kangddong approved these changes
LGTM😊👍

2022-10-26 10:12 UTC, k-nh commented on 1장_깨끗한_코드/chapter1.md
> +## SOLID 원칙
SOLID 원칙 확인해주셔야 할 것 같습니다 !🧐

2022-10-26 10:27 UTC, k-nh requested changes

2022-10-26 10:27 UTC, k-nh commented on 1장_깨끗한_코드/chapter1.md
> +> 나쁜 코드로 계속 작성하는 경웨 보이는 생산성 대 시간 그래프
경웨 >> 오타 있습니당

2022-10-26 10:27 UTC, k-nh commented on 1장_깨끗한_코드/chapter1.md
> +진짜 전문가는 이 말이 틀렸다는 사실을 잘 안다. **나쁜 코드를 양산하면 기한을 맞추지 못한다. **
띄어쓰기 때문에 볼드체가 적용되지 않은 것 같아요 (상관은 없지만.. 의도하신 바가 아니라면)

2022-10-26 12:12 UTC, gaeng2y commented
집 도착해서 수정하겠씁니다 호호

2022-10-26 12:12 UTC, gaeng2y commented on 1장_깨끗한_코드/chapter1.md
> +진짜 전문가는 이 말이 틀렸다는 사실을 잘 안다. **나쁜 코드를 양산하면 기한을 맞추지 못한다. **
집 도착해서 수정하겠씁니다 호호

2022-10-26 12:33 UTC, gaeng2y commented on 1장_깨끗한_코드/chapter1.md
> +## SOLID 원칙
솔리드 원칙이 어떤 것인지에 대한 정의같은 거를 추가하는게 좋을까요!?

2022-10-26 13:06 UTC, k-nh commented on 1장_깨끗한_코드/chapter1.md
> +## SOLID 원칙
5가지 다 SRP 원칙 설명으로 작성이 되어있어서 남긴 리뷰였습니다만 ㅎㅎ 말씀하신 부분 추가하시면 더 좋을 것 같긴 하네요 역쉬 👍

2022-10-26 14:48 UTC, k-nh approved these changes
고생하셨습니다 👍

2022-10-26 14:50 UTC, gaeng2y commented
@k-nh 엥 잘못 눌러서 approve 취소돼서 다시 한번 부탁들여요 헤헿....

2022-10-26 14:57 UTC, k-nh approved these changes

2022-10-27 05:25 UTC, heejin342 approved these changes
첫 스타트 부담되실텐데 고생많으셔씀다.

2022-10-27 05:31 UTC, merged