2022 10 30 3장 함수
LetsSwifty/clean-code pull request #7
Opened 2022-10-30 13:00 UTC by kangddong

2022 10 30 3장 함수
시간이 오래 걸린거에 비해 만족스럽게 정리를 못한 것 같네요
3장 함수에 나오는 내용처럼 초안을 작성한 후에 리뷰를 통해 보완해보겠습니다 !

2022-10-30 16:32 UTC, gaeng2y requested changes

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +내가 함수를 짤 때도 마찬가지다. 처음에는 길고 복잡하다. 들여쓰기 단계도 많고 중복된 루프도 많다. 인수 목록도 아주 길다. 이름은 즉흥적이고 코드는 중 복된다.
`중 복` 띄어쓰기 오타 났어요!

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +하지만 나는 그 서투른 코드를 빠짐없이 테스트하는 단위 테스트 케이 스도 만든다.
여기 `케이 스` 두

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +그런 다음 나는 코드를 다듬고, 함수를 만들고, 이름을 바꾸고, 중복을 제거한 다. 메서드를 줄이고 순서를 바꾼다. 때로는 전체 클래스를 쪼개기도 한다. 이 와중에도 코드는 항상 단위 테스트를 통과한다
`제거한 다` 여기도요!

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +코드 구조에 혼란을 일으키며, 정상 동작과 오유 처리 동작을 뒤섞는다.
오유 -> 오류

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +그러므로 try/catch 블룩을 별도 함수로 뽑아내는 편이 좋다.
블룩 -> 블록

2022-10-30 16:32 UTC, gaeng2y commented on 3장_함수/chapter3.md
> +    else {
여기 스코프가 이상해요! 
} 가 빠진듯하네요

2022-10-30 19:15 UTC, heejin342 commented on 3장_함수/chapter3.md
> +함수 이름만 봐서는 세션을 초기화한다는 사실이 드러나지 않는다.
함수 이름만 봐서는 "비밀번호가 일치할 때? 성공할때?" 세션을 초기화 한다는 사실이 드러나지 않는다. 
로 하면 조금 더 이해가 잘될 것 같습니다!

2022-10-30 19:17 UTC, heejin342 commented on 3장_함수/chapter3.md
> +    deletePage(page)
이 deletePage 함수는 244번째 줄의 delete 함수 맞나요? 아니면 다른 의미를 가지는 함수인가요..!

2022-10-30 19:19 UTC, heejin342 commented on 3장_함수/chapter3.md
> +오류 코드 대신 예외를 사용하면 새 예외는 Exception 클래스에서 파생된다따라서 재컴파일/재배치 없이도 새 예외 클래스를 추가할 수 있다.
파생된다 따라서 띄어쓰기 해주세요!

2022-10-30 19:23 UTC, heejin342 commented on 3장_함수/chapter3.md
> +오류 코드 대신 예외를 사용하면 새 예외는 Exception 클래스에서 파생된다따라서 재컴파일/재배치 없이도 새 예외 클래스를 추가할 수 있다.
이부분 저는 
Error enum에 케이스 하나를 추가할 때, try~catch를 사용하지 않고 오류 처리를 하는경우, 오류처리를 하는 switch 문마다 각각 새로 추가된 enum 에대한 에러 케이스 추가를 해줘야하는데, try~catch를 사용하는 경우는 catch{} 내에서 호출하는 메소드에서 딱 한번만 새로 추가된 enum 케이스 처리를 수정해주면 된다. 라고 이해했습니다. 혹시 비슷한지 여쭤보고 싶습니다!

2022-10-30 22:58 UTC, k-nh commented on 3장_함수/chapter3.md
> +물론 다형성을 이용한다.
"피할 방법이 없다. 물론 다형성을 이용한다." 가 글의 요지와는 조금 다른 의미로 해석될 수도 있을 것 같아요. "switch 문을 완전히 피할 수 없기에, 다형성을 이용하여 저차원 클래스에 숨겨 반복하지 않도록 한다."라는 식으로 작성하는 건 어떨까요 ?!

2022-10-30 22:58 UTC, k-nh commented on 3장_함수/chapter3.md
> +3개(삼항)는 가능한 피하는 편이 좋다. 4개(다항) 이상은 특별한 이유가 필요하다. 특별한 이유가 있어도 사용하면 안 된다.
사용하면 안 되는 이유에 대한 설명이 덧붙여진다면 더 좋을 거 같아용

2022-10-30 22:58 UTC, k-nh commented on 3장_함수/chapter3.md
> +플래그 인수는 추하다.
여기도 지양해야 하는 이유에 대한 설명이 필요할 것 같아요

2022-10-31 06:57 UTC, kangddong commented on 3장_함수/chapter3.md
> +    deletePage(page)
다릅니다

2022-10-31 07:02 UTC, kangddong commented on 3장_함수/chapter3.md
> +    deletePage(page)
다릅니다 !
책에 나온 리팩토링 이전 코드의 흐름은 이렇습니다
1. deletePage(page)  -> registry.deleteReference(page.name) -> configkeys.deleteKey(page. name, makeKey())->  ("page deleted")

명령/조회를 구분하게끔 만든 delete(page: Page) 함수를 호출하고 조회(Error를 throw) / 명령(Error Handling) 이렇게 이해하고 작성했습니다!

2022-10-31 07:09 UTC, kangddong commented on 3장_함수/chapter3.md
> +오류 코드 대신 예외를 사용하면 새 예외는 Exception 클래스에서 파생된다따라서 재컴파일/재배치 없이도 새 예외 클래스를 추가할 수 있다.
네 저도 그렇게 이해했습니다. 책의 있는 말의 의미를 살리면서 줄여보려고했는데 그 와중에

2022-10-31 08:56 UTC, heejin342 approved these changes
수고 많으셨습니다 :> !

2022-10-31 12:25 UTC, gaeng2y approved these changes

2022-10-31 15:23 UTC, kangddong commented on 3장_함수/chapter3.md
> +물론 다형성을 이용한다.
Swift에서 다형성을 통한 Switch문 표현에 대해서 하루종일 고민을 했었는데, ,,추상 팩토리 패턴을 적용하는 것도 적절하게 변환하지 못할 거 같아서 나희님 의견대로 개념만 보충했습니다 !

2022-10-31 15:28 UTC, k-nh commented on 3장_함수/chapter3.md
> +물론 다형성을 이용한다.
최고십니당

2022-10-31 15:28 UTC, k-nh approved these changes

2022-10-31 17:32 UTC, merged