2022 11 3 5장 형식 맞추기
LetsSwifty/clean-code pull request #9
Opened 2022-11-02 17:48 UTC by heejin342

5장 완료했습니다. 키보드를 바꿨더니 오타가 많이 나서 힘들었네요 ㅠ 꼼꼼히 확인 부탁드려요!

2022-11-02 17:55 UTC, heejin342 commented on README.md
> +| :-------: | ------------------------------------------------ | ---------------------------- | :---------------: |
이거 제가 사용하는 에디터에서 save 할때 간격 지 맘대로 바꿔서 저장하더라고요. prettier 때문인거 같은데 ...

2022-11-02 19:45 UTC, gaeng2y requested changes

2022-11-02 19:45 UTC, gaeng2y commented on 5장_형식_맞추기/chapter5.md
> +    func getPageNameOrDefault(request: Request) {
-> Type 이 없긴한데 뭐로 리턴할 줄 몰라서 애매하네용...

2022-11-02 19:45 UTC, gaeng2y commented on 5장_형식_맞추기/chapter5.md
> +func measureLine(_ line: String) {
인덴트가 안맞아서 맞쳐주시면 감사....

2022-11-02 19:45 UTC, gaeng2y commented on 5장_형식_맞추기/chapter5.md
> +func root1(a: Double, b: Double, c: Double) {
요기두...

2022-11-02 19:45 UTC, gaeng2y commented on README.md
> +| :-------: | ------------------------------------------------ | ---------------------------- | :---------------: |
잉 뭐 크게 문제 될 것 같지는 않네유

2022-11-03 06:21 UTC, kangddong commented on 5장_형식_맞추기/chapter5.md
> +import Foundation
UIKit가 Foundation 프레임워크를 포함한 umbrella 프레임워크이니까 Foundation import 안해도 괜찮지않을까요 ?

2022-11-03 06:34 UTC, kangddong commented on 5장_형식_맞추기/chapter5.md
> +	return (-b + Math.sqrt(determinant()) / (2*a)
return (-b + Math.sqrt(determinant()) / (2*a))
오른쪽 맨 끝에 괄호가 덜 닫힌거 같아요 !

2022-11-03 06:39 UTC, k-nh reviewed
수고하셨습니당 🙌

2022-11-04 05:47 UTC, kangddong requested changes
고생하셨습니다 !

2022-11-04 11:44 UTC, gaeng2y approved these changes
수고하셨어요~

2022-11-04 16:43 UTC, heejin342 commented on 5장_형식_맞추기/chapter5.md
> +func root1(a: Double, b: Double, c: Double) {
와,,, 이게 뭐죠 왜 이렇게 한거지... 수정하겠습니다.

2022-11-04 16:45 UTC, heejin342 commented on 5장_형식_맞추기/chapter5.md
> +	return (-b + Math.sqrt(determinant()) / (2*a)
갱이님도 찝어주셨는데 실수가 많았네요.. 수정하겠습니다

2022-11-04 16:48 UTC, heejin342 commented on README.md
> +|  챕터 5   | [형식 맞추기](5장_형식_맞추기/chapter5.md)       |                              | [히진][heejin342] |
깃헙 닉넴이 저거라 저걸루 했어요!

2022-11-05 05:09 UTC, k-nh approved these changes

2022-11-05 10:37 UTC, kangddong approved these changes
고생하셨습니다 !!

2022-11-05 15:13 UTC, merged